name: SonarQube Code Scan

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  sonar-scan:
    runs-on: ubuntu-latest  # Use a Linux runner
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java (required for Maven builds)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Choose JDK distribution
          java-version: '21'       # Set the Java version

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Run SonarQube analysis
      - name: SonarQube Scan
        run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
